# Generated by Django 3.0.3 on 2020-09-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0002_auto_20200921_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='inventario_app.Category', verbose_name='categoria'),
        ),
    ]
