# Generated by Django 3.0.3 on 2020-09-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0004_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
