# Generated by Django 3.0.3 on 2020-10-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0006_auto_20201009_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='costumer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
