# Generated by Django 3.1.3 on 2020-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0009_auto_20201109_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='gift',
            field=models.BooleanField(default=False),
        ),
    ]
