# Generated by Django 3.1.3 on 2020-11-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0010_auto_20201113_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=255, verbose_name='descripcion'),
        ),
    ]
