# Generated by Django 3.1.3 on 2020-11-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0013_auto_20201116_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='chocolate.jpg', null=True, upload_to='static/images/', verbose_name='imagen'),
        ),
    ]
