# Generated by Django 3.1.3 on 2020-11-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0020_product_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='phone',
        ),
    ]
