# Generated by Django 3.1.3 on 2020-11-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0021_remove_product_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='descripcion'),
        ),
    ]
