# Generated by Django 3.1.3 on 2020-11-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0023_auto_20201124_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='chocolate.jpg', null=True, upload_to='', verbose_name='imagen'),
        ),
    ]
