# Generated by Django 3.1.3 on 2020-11-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0025_auto_20201125_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='chocolate.jpg', null=True, upload_to='', verbose_name='imagen'),
        ),
    ]
