# Generated by Django 3.1.3 on 2020-12-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0026_auto_20201125_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
