# Generated by Django 3.1.3 on 2020-12-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0027_auto_20201207_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_by_grams',
            field=models.DecimalField(blank=True, choices=[('100g', 0), ('200g', 0), ('300g', 0)], decimal_places=2, max_digits=5, null=True, verbose_name='precio'),
        ),
    ]
