# Generated by Django 3.1.3 on 2020-12-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0029_remove_product_price_by_grams'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='precio por 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_200g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='precio por 200g'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_300g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='precio por 300g'),
        ),
    ]
