# Generated by Django 3.1.3 on 2020-12-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0030_auto_20201215_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_by_weight',
            field=models.BooleanField(default=False),
        ),
    ]
