# Generated by Django 3.1.3 on 2020-12-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0032_auto_20201216_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sold_by_weight_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
