# Generated by Django 3.1.3 on 2020-12-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0033_orderitem_sold_by_weight_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
